version: "3"

networks:
  laravel:
    driver: bridge

volumes:
  app-mysql:
    driver: local
  app-redis:
    driver: local
  app-meilisearch:
    driver: local

services:
  app:
    env_file:
      - .env
    container_name: laravel-app
    image: laravel
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
      args:
        - USER=${USER}
        - UID=${UID:-1000}
        - NODE_VERSION=${NODE_VERSION:-18}
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    depends_on:
      - redis
      - mysql
      - mailpit
    networks:
      - laravel
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3308}:3308"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "app-mysql:/var/lib/mysql"
      - "./dockerfiles/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - laravel
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - ./src:/var/www
      - ./dockerfiles/nginx:/etc/nginx/conf.d/
    networks:
      - laravel
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - "app-redis:/data"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    networks:
      - laravel
  npm:
    image: node:alpine
    volumes:
      - ./src:/var/www
    ports:
      - "${FORWARD_NPM_PORT1:-3000}:3000"
      - "${FORWARD_NPM_PORT2:-3001}:3001"
      - "${FORWARD_NPM_PORT3:-5174}:5174"
    working_dir: /var/www
    entrypoint: ["npm"]
    networks:
      - laravel
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
        - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
        - 'app-meilisearch:/meili_data'
    networks:
        - laravel
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:${FORWARD_MEILISEARCH_PORT}/health'
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
        - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
        - laravel
